// Generated by CoffeeScript 1.10.0
(function() {
  var name;

  name = "Joseph";

  if (name.length > 1) {
    console.log("HELLO, " + name + "!");
  } else {
    console.log("empty name");
  }

}).call(this);
